cmake_minimum_required(VERSION 3.20)

if(NOT BACKEND MATCHES "^(cuda|metal)$")
    message(FATAL_ERROR "BACKEND must be cuda or metal")
endif()
include("${MODULE}")

if(TRANSFORM_ONLY)
    cmake_language(CALL "gliner_${BACKEND}_f32_source" "${INPUT}" "${OUTPUT}")
    return()
endif()

if(BACKEND STREQUAL "cuda")
    set(filename "ggml-cuda.cu")
    set(original_pattern "if (ggml_cuda_should_use_mmf(src0->type, cc, warp_size, src0->ne, src0->nb, ne11, /*mul_mat_id =*/ false)) {")
    set(fixed_pattern "if (ggml_get_op_params_i32(dst, 3) != GGML_PREC_F32 &&\n        ggml_cuda_should_use_mmf(src0->type, cc, warp_size, src0->ne, src0->nb, ne11, /*mul_mat_id =*/ false)) {")
    set(original "void dispatch() {\n    ${original_pattern}\n        multiply();\n    }\n}\n")
    set(unsupported "Unsupported GGML CUDA dispatch")
else()
    set(filename "ggml-metal-common.cpp")
    set(original_pattern "    return !ggml_is_transposed(op->src[0]) &&")
    set(fixed_pattern "    return !(op->src[0]->type == GGML_TYPE_F32 &&\n             op->src[1]->type == GGML_TYPE_F32 &&\n             ggml_get_op_params_i32(op, 0) == GGML_PREC_F32) &&\n           !ggml_is_transposed(op->src[0]) &&")
    set(original "bool use_mm() {\n${original_pattern}\n        true;\n}\n")
    set(unsupported "Unsupported GGML Metal matrix dispatch")
endif()

file(MAKE_DIRECTORY "${WORK_DIR}")
set(input "${WORK_DIR}/${filename}")
set(output "${WORK_DIR}/patched-${filename}")
string(REPLACE "${original_pattern}" "${fixed_pattern}" patched "${original}")

function(assert_contents path expected)
    file(READ "${path}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Unexpected contents: ${path}")
    endif()
endfunction()

function(transform expected_error)
    execute_process(
        COMMAND "${CMAKE_COMMAND}" "-DBACKEND=${BACKEND}" "-DMODULE=${MODULE}"
            "-DINPUT=${input}" "-DOUTPUT=${output}" -DTRANSFORM_ONLY=ON
            -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
    if(expected_error STREQUAL "")
        if(NOT result STREQUAL "0")
            message(FATAL_ERROR "Transformation failed:\n${stdout}\n${stderr}")
        endif()
    else()
        string(FIND "${stderr}" "${expected_error}" found)
        if(result STREQUAL "0" OR found EQUAL -1)
            message(FATAL_ERROR "Expected '${expected_error}', got:\n${stdout}\n${stderr}")
        endif()
    endif()
endfunction()

file(WRITE "${input}" "${original}")
transform("")
assert_contents("${input}" "${original}")
assert_contents("${output}" "${patched}")
transform("")
assert_contents("${output}" "${patched}")
file(WRITE "${input}" "${patched}")
transform("")
assert_contents("${input}" "${patched}")
assert_contents("${output}" "${patched}")
file(WRITE "${input}" "void unrelated_dispatch() {}\n")
transform("${unsupported}")
file(WRITE "${input}" "${original}${original}")
transform("${unsupported}")
file(WRITE "${input}" "${original}${patched}")
transform("Mixed patched and unpatched")
file(WRITE "${input}" "${original}")
file(WRITE "${WORK_DIR}/other.cpp" "void other() {}\n")

set(project [=[
cmake_minimum_required(VERSION 3.20)
project(precision_overlay LANGUAGES CXX)
include("@MODULE@")
add_library(ggml-@BACKEND@ STATIC @filename@ other.cpp)
set_target_properties(ggml-@BACKEND@ PROPERTIES LINKER_LANGUAGE CXX)
gliner_fix_@BACKEND@_precision()
get_target_property(sources ggml-@BACKEND@ SOURCES)
file(WRITE "${CMAKE_BINARY_DIR}/sources.txt" "${sources}")
get_target_property(includes ggml-@BACKEND@ INCLUDE_DIRECTORIES)
file(WRITE "${CMAKE_BINARY_DIR}/includes.txt" "${includes}")
set_source_files_properties(${sources} PROPERTIES LANGUAGE CXX)
]=])
file(CONFIGURE OUTPUT "${WORK_DIR}/CMakeLists.txt" CONTENT "${project}" @ONLY)
execute_process(
    COMMAND "${CMAKE_COMMAND}" -S "${WORK_DIR}" -B "${WORK_DIR}/build"
        "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Overlay target configuration failed:\n${stdout}\n${stderr}")
endif()
assert_contents("${input}" "${original}")
assert_contents("${WORK_DIR}/build/gliner-${BACKEND}/${filename}" "${patched}")
file(READ "${WORK_DIR}/build/sources.txt" sources)
list(LENGTH sources count)
if(NOT count EQUAL 2)
    message(FATAL_ERROR "Unexpected overlay target source count: ${sources}")
endif()
list(GET sources 0 first)
list(GET sources 1 second)
if(NOT first STREQUAL "${WORK_DIR}/build/gliner-${BACKEND}/${filename}" OR
        NOT second STREQUAL "other.cpp")
    message(FATAL_ERROR "Unexpected overlay target sources: ${sources}")
endif()
file(READ "${WORK_DIR}/build/includes.txt" includes)
list(FIND includes "${WORK_DIR}" include_index)
if(include_index EQUAL -1)
    message(FATAL_ERROR "Original source include directory was not preserved")
endif()
message(STATUS "${BACKEND} precision overlay is repeatable and leaves source checkouts unchanged")
