function(gliner_cuda_f32_source input output)
    # GGML v0.24.0's MMF kernel uses TF32/F16 operands regardless of F32 source precision.
    file(READ "${input}" source)
    set(original "if (ggml_cuda_should_use_mmf(src0->type, cc, warp_size, src0->ne, src0->nb, ne11, /*mul_mat_id =*/ false)) {")
    set(fixed "if (ggml_get_op_params_i32(dst, 3) != GGML_PREC_F32 &&\n        ggml_cuda_should_use_mmf(src0->type, cc, warp_size, src0->ne, src0->nb, ne11, /*mul_mat_id =*/ false)) {")
    string(FIND "${source}" "${fixed}" fixed_at)
    string(REPLACE "${original}" "" without_original "${source}")
    string(LENGTH "${source}" source_size)
    string(LENGTH "${without_original}" remaining_size)
    string(LENGTH "${original}" pattern_size)
    math(EXPR matches "(${source_size} - ${remaining_size}) / ${pattern_size}")
    if(fixed_at EQUAL -1)
        if(NOT matches EQUAL 1)
            message(FATAL_ERROR "Unsupported GGML CUDA dispatch for the F32 precision fix. Use pinned GGML v0.24.0.")
        endif()
        string(REPLACE "${original}" "${fixed}" source "${source}")
    elseif(NOT matches EQUAL 0)
        message(FATAL_ERROR "Mixed patched and unpatched GGML CUDA dispatch sources")
    endif()
    file(CONFIGURE OUTPUT "${output}" CONTENT "${source}" @ONLY)
endfunction()

function(gliner_fix_cuda_precision)
    if(NOT TARGET ggml-cuda)
        message(FATAL_ERROR "Strict CUDA precision requires a GGML source build. Populate ggml/ or set GLINER_GGML_SOURCE_DIR.")
    endif()
    get_target_property(imported ggml-cuda IMPORTED)
    if(imported)
        message(FATAL_ERROR "Cannot apply the CUDA precision fix to a prebuilt GGML. Use GLINER_GGML_SOURCE_DIR.")
    endif()
    get_target_property(source_dir ggml-cuda SOURCE_DIR)
    get_target_property(sources ggml-cuda SOURCES)
    set(patched_sources "")
    set(found FALSE)
    foreach(source IN LISTS sources)
        get_filename_component(name "${source}" NAME)
        if(name STREQUAL "ggml-cuda.cu")
            if(found)
                message(FATAL_ERROR "Multiple GGML CUDA dispatch sources found")
            endif()
            get_filename_component(input "${source}" ABSOLUTE BASE_DIR "${source_dir}")
            set(output "${CMAKE_CURRENT_BINARY_DIR}/gliner-cuda/ggml-cuda.cu")
            file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/gliner-cuda")
            gliner_cuda_f32_source("${input}" "${output}")
            list(APPEND patched_sources "${output}")
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${input}")
            set(found TRUE)
        else()
            list(APPEND patched_sources "${source}")
        endif()
    endforeach()
    if(NOT found)
        message(FATAL_ERROR "GGML CUDA dispatch source not found")
    endif()
    set_property(TARGET ggml-cuda PROPERTY SOURCES "${patched_sources}")
    target_include_directories(ggml-cuda PRIVATE "${source_dir}")
    message(STATUS "gliner: applied CUDA F32-input precision fix in the build directory")
endfunction()
