function(gliner_metal_f32_source input output)
    # GGML v0.24.0's F32 Metal MM shader converts both operands to half.
    # Keep F32-requested products on its full-F32 MV shader instead.
    file(READ "${input}" source)
    set(original "    return !ggml_is_transposed(op->src[0]) &&")
    set(fixed "    return !(op->src[0]->type == GGML_TYPE_F32 &&\n             op->src[1]->type == GGML_TYPE_F32 &&\n             ggml_get_op_params_i32(op, 0) == GGML_PREC_F32) &&\n           !ggml_is_transposed(op->src[0]) &&")
    string(FIND "${source}" "${fixed}" fixed_at)
    string(REPLACE "${original}" "" without_original "${source}")
    string(LENGTH "${source}" source_size)
    string(LENGTH "${without_original}" remaining_size)
    string(LENGTH "${original}" pattern_size)
    math(EXPR matches "(${source_size} - ${remaining_size}) / ${pattern_size}")
    if(fixed_at EQUAL -1)
        if(NOT matches EQUAL 1)
            message(FATAL_ERROR "Unsupported GGML Metal matrix dispatch for the F32 precision fix. Use pinned GGML v0.24.0.")
        endif()
        string(REPLACE "${original}" "${fixed}" source "${source}")
    elseif(NOT matches EQUAL 0)
        message(FATAL_ERROR "Mixed patched and unpatched GGML Metal dispatch sources")
    endif()
    file(CONFIGURE OUTPUT "${output}" CONTENT "${source}" @ONLY)
endfunction()

function(gliner_fix_metal_precision)
    if(NOT TARGET ggml-metal)
        message(FATAL_ERROR "Strict Metal precision requires a GGML source build. Populate ggml/ or set GLINER_GGML_SOURCE_DIR.")
    endif()
    get_target_property(imported ggml-metal IMPORTED)
    if(imported)
        message(FATAL_ERROR "Cannot apply the Metal precision fix to a prebuilt GGML. Use GLINER_GGML_SOURCE_DIR.")
    endif()
    get_target_property(source_dir ggml-metal SOURCE_DIR)
    get_target_property(sources ggml-metal SOURCES)
    set(patched_sources "")
    set(found FALSE)
    foreach(source IN LISTS sources)
        get_filename_component(name "${source}" NAME)
        if(name STREQUAL "ggml-metal-common.cpp")
            if(found)
                message(FATAL_ERROR "Multiple GGML Metal matrix dispatch sources found")
            endif()
            get_filename_component(input "${source}" ABSOLUTE BASE_DIR "${source_dir}")
            set(output "${CMAKE_CURRENT_BINARY_DIR}/gliner-metal/ggml-metal-common.cpp")
            file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/gliner-metal")
            gliner_metal_f32_source("${input}" "${output}")
            list(APPEND patched_sources "${output}")
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${input}")
            set(found TRUE)
        else()
            list(APPEND patched_sources "${source}")
        endif()
    endforeach()
    if(NOT found)
        message(FATAL_ERROR "GGML Metal matrix dispatch source not found")
    endif()
    set_property(TARGET ggml-metal PROPERTY SOURCES "${patched_sources}")
    target_include_directories(ggml-metal PRIVATE "${source_dir}")
    message(STATUS "gliner: applied Metal F32 matrix precision fix in the build directory")
endfunction()
